[build]
    publish = "exampleSite/public"

[build.environment]
    HUGO_VERSION = "0.82.0"
    HUGO_THEME = "repo"

[context.production]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[[plugins]]
    package = "/exampleSite/plugins/netlify-plugin-hugo-cache-resources"


# [build]
# publish = "public"
# command = "hugo --gc --minify"

# [context.production.environment]
# HUGO_VERSION = "0.82.0"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"

# [context.split1]
# command = "hugo --gc --minify --enableGitInfo"

# [context.split1.environment]
# HUGO_VERSION = "0.82.0"
# HUGO_ENV = "production"

# [context.deploy-preview]
# command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# [context.deploy-preview.environment]
# HUGO_VERSION = "0.82.0"

# [context.branch-deploy]
# command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# [context.branch-deploy.environment]
# HUGO_VERSION = "0.82.0"

# [context.next.environment]
# HUGO_ENABLEGITINFO = "true"
